namespace ReplayFoundry.Desktop.Media.Transcription;

// Token order follows whisper.cpp v1.7.5 g_lang. Older multilingual
// vocabularies contain the first 99 languages; v3 also contains Cantonese.
// https://github.com/ggml-org/whisper.cpp/blob/v1.7.5/src/whisper.cpp
public sealed record WhisperLanguageDefinition(string Code, string PolicyName, string DisplayName, int TokenIndex);

public static class WhisperLanguageCatalog
{
    public static IReadOnlyList<WhisperLanguageDefinition> Languages { get; } = Array.AsReadOnly<WhisperLanguageDefinition>(
    [
        new("en", "English", "English", 0),
        new("zh", "Chinese", "Chinese", 1),
        new("de", "German", "German", 2),
        new("es", "Spanish", "Spanish", 3),
        new("ru", "Russian", "Russian", 4),
        new("ko", "Korean", "Korean", 5),
        new("fr", "French", "French", 6),
        new("ja", "Japanese", "Japanese", 7),
        new("pt", "Portuguese", "Portuguese", 8),
        new("tr", "Turkish", "Turkish", 9),
        new("pl", "Polish", "Polish", 10),
        new("ca", "Catalan", "Catalan", 11),
        new("nl", "Dutch", "Dutch", 12),
        new("ar", "Arabic", "Arabic", 13),
        new("sv", "Swedish", "Swedish", 14),
        new("it", "Italian", "Italian", 15),
        new("id", "Indonesian", "Indonesian", 16),
        new("hi", "Hindi", "Hindi", 17),
        new("fi", "Finnish", "Finnish", 18),
        new("vi", "Vietnamese", "Vietnamese", 19),
        new("he", "Hebrew", "Hebrew", 20),
        new("uk", "Ukrainian", "Ukrainian", 21),
        new("el", "Greek", "Greek", 22),
        new("ms", "Malay", "Malay", 23),
        new("cs", "Czech", "Czech", 24),
        new("ro", "Romanian", "Romanian", 25),
        new("da", "Danish", "Danish", 26),
        new("hu", "Hungarian", "Hungarian", 27),
        new("ta", "Tamil", "Tamil", 28),
        new("no", "Norwegian", "Norwegian", 29),
        new("th", "Thai", "Thai", 30),
        new("ur", "Urdu", "Urdu", 31),
        new("hr", "Croatian", "Croatian", 32),
        new("bg", "Bulgarian", "Bulgarian", 33),
        new("lt", "Lithuanian", "Lithuanian", 34),
        new("la", "Latin", "Latin", 35),
        new("mi", "Maori", "Maori", 36),
        new("ml", "Malayalam", "Malayalam", 37),
        new("cy", "Welsh", "Welsh", 38),
        new("sk", "Slovak", "Slovak", 39),
        new("te", "Telugu", "Telugu", 40),
        new("fa", "Persian", "Persian", 41),
        new("lv", "Latvian", "Latvian", 42),
        new("bn", "Bengali", "Bengali", 43),
        new("sr", "Serbian", "Serbian", 44),
        new("az", "Azerbaijani", "Azerbaijani", 45),
        new("sl", "Slovenian", "Slovenian", 46),
        new("kn", "Kannada", "Kannada", 47),
        new("et", "Estonian", "Estonian", 48),
        new("mk", "Macedonian", "Macedonian", 49),
        new("br", "Breton", "Breton", 50),
        new("eu", "Basque", "Basque", 51),
        new("is", "Icelandic", "Icelandic", 52),
        new("hy", "Armenian", "Armenian", 53),
        new("ne", "Nepali", "Nepali", 54),
        new("mn", "Mongolian", "Mongolian", 55),
        new("bs", "Bosnian", "Bosnian", 56),
        new("kk", "Kazakh", "Kazakh", 57),
        new("sq", "Albanian", "Albanian", 58),
        new("sw", "Swahili", "Swahili", 59),
        new("gl", "Galician", "Galician", 60),
        new("mr", "Marathi", "Marathi", 61),
        new("pa", "Punjabi", "Punjabi", 62),
        new("si", "Sinhala", "Sinhala", 63),
        new("km", "Khmer", "Khmer", 64),
        new("sn", "Shona", "Shona", 65),
        new("yo", "Yoruba", "Yoruba", 66),
        new("so", "Somali", "Somali", 67),
        new("af", "Afrikaans", "Afrikaans", 68),
        new("oc", "Occitan", "Occitan", 69),
        new("ka", "Georgian", "Georgian", 70),
        new("be", "Belarusian", "Belarusian", 71),
        new("tg", "Tajik", "Tajik", 72),
        new("sd", "Sindhi", "Sindhi", 73),
        new("gu", "Gujarati", "Gujarati", 74),
        new("am", "Amharic", "Amharic", 75),
        new("yi", "Yiddish", "Yiddish", 76),
        new("lo", "Lao", "Lao", 77),
        new("uz", "Uzbek", "Uzbek", 78),
        new("fo", "Faroese", "Faroese", 79),
        new("ht", "HaitianCreole", "Haitian Creole", 80),
        new("ps", "Pashto", "Pashto", 81),
        new("tk", "Turkmen", "Turkmen", 82),
        new("nn", "Nynorsk", "Nynorsk", 83),
        new("mt", "Maltese", "Maltese", 84),
        new("sa", "Sanskrit", "Sanskrit", 85),
        new("lb", "Luxembourgish", "Luxembourgish", 86),
        new("my", "Burmese", "Burmese", 87),
        new("bo", "Tibetan", "Tibetan", 88),
        new("tl", "Tagalog", "Tagalog", 89),
        new("mg", "Malagasy", "Malagasy", 90),
        new("as", "Assamese", "Assamese", 91),
        new("tt", "Tatar", "Tatar", 92),
        new("haw", "Hawaiian", "Hawaiian", 93),
        new("ln", "Lingala", "Lingala", 94),
        new("ha", "Hausa", "Hausa", 95),
        new("ba", "Bashkir", "Bashkir", 96),
        new("jw", "Javanese", "Javanese", 97),
        new("su", "Sundanese", "Sundanese", 98),
        new("yue", "Cantonese", "Cantonese", 99),
    ]);
}
