using Editor = ReplayFoundry.Desktop.Features.Studio.Editorial.StudioEditorialMetadataViewModel;

namespace ReplayFoundry.Desktop.Features.Studio.Editorial;

internal static class StudioEditorialPropertyNotifications
{
    internal static readonly string[] All =
    [
        nameof(Editor.Title),
        nameof(Editor.Description),
        nameof(Editor.Tags),
        nameof(Editor.AudienceAddress),
        nameof(Editor.NamingGuidance),
        nameof(Editor.DescriptionSignature),
        nameof(Editor.TitleCharacterCount),
        nameof(Editor.DescriptionCharacterCount),
        nameof(Editor.PackagingGuidance),
        nameof(Editor.CopyVersions),
        nameof(Editor.HasCopyVersions),
        nameof(Editor.SelectedCopyVersion),
        nameof(Editor.SelectedCopyPreview),
        nameof(Editor.Status),
        nameof(Editor.HasCopyReview),
        nameof(Editor.DraftState),
        nameof(Editor.MetadataOriginText),
        nameof(Editor.WhyThisTitleText),
        nameof(Editor.NeedsCurrentCutRefresh),
        nameof(Editor.CurrentCutStatus),
        nameof(Editor.HasContextReceipt),
        nameof(Editor.ContextUsedSummary),
        nameof(Editor.ContextAuthoritySummary),
        nameof(Editor.ContextNeedsReview),
        nameof(Editor.ContextReviewSummary),
        nameof(Editor.CanonicalGameContextText),
        nameof(Editor.GameContextFreshnessText),
        nameof(Editor.HasGameContextSources),
        nameof(Editor.GameContextSourcesText),
        nameof(Editor.HasSupportedGameContextClaims),
        nameof(Editor.SupportedGameContextClaimsText),
        nameof(Editor.HasAmbiguousGameContextSuggestions),
        nameof(Editor.AmbiguousGameContextSuggestionsText),
        nameof(Editor.GameContextComponentsText),
        nameof(Editor.CanRefreshPublicGameContext),
        nameof(Editor.HasCachedPublicGameContext),
        nameof(Editor.IsGameContextUpdating),
        nameof(Editor.RefreshCurrentCutText),
        nameof(Editor.HasUnsavedChanges),
        nameof(Editor.HasUnsavedProfileChanges),
        nameof(Editor.SaveButtonText),
        nameof(Editor.SaveGuidance),
        nameof(Editor.IsGenerating),
        nameof(Editor.IsAiAvailable),
        nameof(Editor.UsesLocalAiForRerolls),
        nameof(Editor.RerollButtonText),
        nameof(Editor.RerollAutomationName),
        nameof(Editor.RerollProviderText),
        nameof(Editor.VariantChoices),
        nameof(Editor.SelectedVariantChoice),
        nameof(Editor.SelectedVariantDescription),
    ];
}
